require('dotenv').config();

const {
  OPENAI_API_KEY,
  OPENAI_MAX_TOKENS,
  OPENAI_CONTENT,
  CACHE_HOST,
  CACHE_PORT,
  CACHE_PASSWORD,
} = process.env;

module.exports = {
  OPENAI_API_KEY,
  OPENAI_MAX_TOKENS,
  OPENAI_CONTENT,
  CACHE_HOST,
  CACHE_PORT,
  CACHE_PASSWORD,
};
